#!/usr/bin/env python3
# Copyright 2026 Politecnico di Torino
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# pre_build hook of the `asic_dc_synthesis_<tech>` fusesoc targets.
#
# Design Compiler splits a top-level port of struct type into one port per
# member (`ext_xbar_master_req_i[0][addr]`, ...), while Yosys/slang keeps it
# as one packed vector with the RTL name. The post-synthesis testbench
# connects `x_heep_system` by the RTL port names, so DC synthesizes this
# wrapper instead, `x_heep_system_dc_top`:
#   - the same parameter and port list as `x_heep_system` (as generated by
#     `make mcu-gen`, without the CV-X-IF interface ports: XHEEP_STANDALONE_SYNTHESIS),
#     every port of a non-plain type re-declared as a plain packed `logic`
#     vector of the same width;
#   - an `x_heep_system` instance, every port connected by name.
# dc_script.tcl renames it to `x_heep_system` (and the RTL top to
# `x_heep_system_core`) before writing the netlist, whose top then has the
# same name, port names and widths as the Yosys one.

import re
import sys
from pathlib import Path

SRC = Path("../../../hw/system/x_heep_system.sv")
OUT = Path("x_heep_system_dc_top.sv")
TOP = "x_heep_system_dc_top"

# One port declaration per line: `<dir> <type> [dims...] <name>[,] [// ...]`
PORT_RE = re.compile(
    r"^(?P<indent>\s*)(?P<dir>input|output|inout)\s+"
    r"(?P<type>[A-Za-z_]\w*(?:::[A-Za-z_]\w*)?)\s*"
    r"(?P<dims>(?:\[[^\]]*\]\s*)*)"
    r"(?P<name>[A-Za-z_]\w*)\s*(?P<comma>,?)\s*(?://.*)?$"
)
DIR_RE = re.compile(r"^\s*(input|output|inout)\b")
XIF_RE = re.compile(r"\bif_xif\s*\.\s*cpu_\w+\s+xif_\w+_if\b")
PLAIN_TYPES = {"logic", "wire", "reg", "bit", "tri"}


def extract_header(text: str) -> str:
    """The full `module x_heep_system #( ... ) ( ... );` header, by tracking
    the parenthesis depth up to the terminating top-level ';'."""
    m = re.search(r"\bmodule\s+x_heep_system\b", text)
    if m is None:
        sys.exit(f"ERROR: 'module x_heep_system' not found in {SRC}")
    depth = 0
    seen_paren = False
    for i in range(m.end(), len(text)):
        c = text[i]
        if c == "(":
            depth += 1
            seen_paren = True
        elif c == ")":
            depth -= 1
        elif c == ";" and seen_paren and depth == 0:
            return text[m.start() : i + 1]
    sys.exit(f"ERROR: end of the 'module x_heep_system' header not found in {SRC}")


def main() -> None:
    if not SRC.exists():
        sys.exit(f"ERROR: {SRC} not found: run 'make mcu-gen' first.")
    header = extract_header(SRC.read_text())

    lines = []
    names = []
    for line in header.splitlines():
        stripped = line.strip()
        # The CV-X-IF interface ports and their `ifndef XHEEP_STANDALONE_SYNTHESIS guard
        if XIF_RE.search(line) or stripped.startswith(("`ifndef XHEEP_STANDALONE_SYNTHESIS", "`endif")):
            continue
        if stripped.startswith("`"):
            sys.exit(f"ERROR: unsupported preprocessor directive in the port list of {SRC}:\n  {stripped}")
        if not DIR_RE.match(line):
            lines.append(line)
            continue
        m = PORT_RE.match(line)
        if m is None:
            sys.exit(f"ERROR: unsupported port declaration in {SRC}:\n  {stripped}")
        names.append(m["name"])
        if m["type"] in PLAIN_TYPES:
            lines.append(line)
        else:
            dims = re.sub(r"\s+", "", m["dims"])
            lines.append(
                f"{m['indent']}{m['dir']} logic {dims}[$bits({m['type']})-1:0] {m['name']}{m['comma']}"
            )

    text = "\n".join(lines).replace("module x_heep_system", f"module {TOP}", 1)
    # A trailing comma left before ')' by the removed lines
    text = re.sub(r",(\s*)\)\s*;\s*$", r"\1);", text)
    conns = ",\n".join(f"      .{n}({n})" for n in names)

    OUT.write_text(
        f"""\
// Auto-generated by scripts/synthesis/dc/generate_dc_top.py from {SRC}
// - do not edit. Design Compiler top: x_heep_system with plain-vector ports.

{text}

  x_heep_system x_heep_system_i (
{conns}
  );

endmodule
"""
    )
    print(f"[generate_dc_top] wrote {OUT} ({len(names)} ports)")


if __name__ == "__main__":
    main()
