#!/usr/bin/env python3
# Copyright EPFL contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Run by `make yosys-ihp130-stage-netlist` (NOT a fusesoc pre_build hook:
# the `sim_postsynthesis` fusesoc target needs this file to already exist as
# a real, static fileset member when fusesoc parses core-v-mini-mcu.core, so
# it must be generated at staging time, same as the netlist copy itself).
#
# The Yosys/IHP-SG13G2 netlist's top module is `x_heep_system_synth_top`
# (see edalize_yosys_template.tcl): after `-flatten`, synthesis elaborates
# away all of `x_heep_system`'s parameters, so it can no longer accept the
# parameter overrides `testharness.sv` passes when instantiating
# `x_heep_system` (EXT_XBAR_NMASTER, obi_req_t, ...) - QuestaSim fails with
# "Module parameter 'X' not found for override".
#
# This script generates a simulation-only shim: module `x_heep_system`, with
# the EXACT SAME parameter/port list as the real (RTL) `x_heep_system`
# (extracted verbatim from hw/system/x_heep_system.sv, so it always matches
# whatever `mcu-gen` produced), that simply instantiates the real netlist
# (`x_heep_system_synth_top`) via `.*` - the shim's own parameters are inert
# (never forwarded), and any of its ports absent from the netlist (the 6
# `if_xif` interface ports, tied off during synthesis - see
# generate_xif_tieoff_wrapper.py) are simply left unconnected by `.*`.

import re
import sys
from pathlib import Path

SRC = Path("hw/system/x_heep_system.sv")
OUT = Path("implementation/yosys/netlist/x_heep_system_postsyn_sim_shim.sv")


def extract_header(text: str) -> str:
    """Return the full `module x_heep_system #( ... ) ( ... );` header
    (parameter list + port list), by tracking paren depth from the module
    keyword to the terminating top-level ';'."""
    m = re.search(r"\bmodule\s+x_heep_system\b", text)
    if m is None:
        sys.exit(f"ERROR: 'module x_heep_system' not found in {SRC}")
    start = m.start()
    depth = 0
    seen_paren = False
    i = m.end()
    while i < len(text):
        c = text[i]
        if c == "(":
            depth += 1
            seen_paren = True
        elif c == ")":
            depth -= 1
        elif c == ";" and seen_paren and depth == 0:
            return text[start : i + 1]
        i += 1
    sys.exit(f"ERROR: could not find end of 'module x_heep_system' header in {SRC}")


def main():
    if not SRC.exists():
        sys.exit(
            f"ERROR: {SRC} not found. Run 'make mcu-gen' before staging the netlist."
        )
    header = extract_header(SRC.read_text())

    shim = f"""\
// Auto-generated by scripts/sim/modelsim/generate_postsyn_sim_shim.py
// from {SRC} - do not edit by hand, re-run the generator instead
// (via `make yosys-ihp130-stage-netlist`).
//
// Simulation-only shim: reintroduces `x_heep_system`'s parameter/port list
// (needed for testharness.sv's instantiation to elaborate) around the real
// post-synthesis netlist, `x_heep_system_synth_top`.

{header}

  x_heep_system_synth_top x_heep_system_synth_top_i (.*);

endmodule
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(shim)
    print(f"[generate_postsyn_sim_shim] Wrote {OUT}")


if __name__ == "__main__":
    main()
