#!/usr/bin/env python3
# Copyright EPFL contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# pre_build hook for the `asic_yosys_synthesis` fusesoc target.
#
# `x_heep_system` cannot be a synthesis top on its own: it exposes 6
# SystemVerilog `interface` ports (the CV-X-IF eXtension Interface,
# `xif_compressed_if` ... `xif_result_if`), and yosys-slang refuses a
# top-level module with an unconnected interface port:
#   "top-level module 'x_heep_system' has unconnected interface port
#    'xif_compressed_if'"
#
# This script generates a thin synthesis-only wrapper, `x_heep_system_synth_top`,
# that:
#   - has the EXACT same parameter list and port list as `x_heep_system`,
#     MINUS the 6 xif interface ports (extracted verbatim by text
#     processing, so it always matches whatever `mcu-gen` produced - no
#     manual upkeep, unlike hw/asic/ihp-sg13g2/rtl/asic_x_heep_system_wrapper.sv);
#   - instantiates `x_heep_system`, binding the 6 xif ports to internal
#     `if_xif` instances (tied off / unused - fine, no CPU extension is
#     enabled in the ASIC synthesis flow) and forwarding every other port
#     1:1 via SystemVerilog's `.*` implicit connection.
#
# edalize_yosys_template.tcl reads this file as an extra source alongside
# files.flist and uses `x_heep_system_synth_top` as the actual synthesis
# top, then renames the synthesized module back to `x_heep_system` before
# writing out the netlist - so the netlist stays a drop-in replacement for
# the RTL `x_heep_system` fileset (same module name AND port list),
# usable unmodified by tb_top/testharness in the `sim_postsynthesis` target.

import re
import sys
from pathlib import Path

SRC = Path("../../../hw/system/x_heep_system.sv")
OUT = Path("x_heep_system_synth_top.sv")

XIF_PORTS = [
    ("xif_compressed_if", "cpu_compressed"),
    ("xif_issue_if", "cpu_issue"),
    ("xif_commit_if", "cpu_commit"),
    ("xif_mem_if", "cpu_mem"),
    ("xif_mem_result_if", "cpu_mem_result"),
    ("xif_result_if", "cpu_result"),
]


def extract_header(text: str) -> str:
    """Return the full `module x_heep_system #( ... ) ( ... );` header
    (parameter list + port list), by tracking paren depth from the module
    keyword to the terminating top-level ';'."""
    m = re.search(r"\bmodule\s+x_heep_system\b", text)
    if m is None:
        sys.exit(f"ERROR: 'module x_heep_system' not found in {SRC}")
    start = m.start()
    depth = 0
    seen_paren = False
    i = m.end()
    while i < len(text):
        c = text[i]
        if c == "(":
            depth += 1
            seen_paren = True
        elif c == ")":
            depth -= 1
        elif c == ";" and seen_paren and depth == 0:
            return text[start : i + 1]
        i += 1
    sys.exit(f"ERROR: could not find end of 'module x_heep_system' header in {SRC}")


def strip_xif_ports(header: str) -> str:
    """Drop the 6 `if_xif.<modport> xif_*_if,` port declaration lines."""
    out_lines = []
    for line in header.splitlines():
        if re.search(r"\bif_xif\s*\.\s*cpu_\w+\s+xif_\w+_if\b", line):
            continue
        out_lines.append(line)
    # Clean up a possible dangling trailing comma left on the last real port
    # (the removed lines were originally followed by more ports+ ')').
    text = "\n".join(out_lines)
    text = re.sub(r",(\s*)\)\s*;\s*$", r"\1);", text)
    return text


def main():
    if not SRC.exists():
        sys.exit(
            f"ERROR: {SRC} not found. Run 'make mcu-gen' before the Yosys ASIC synthesis flow."
        )
    src_text = SRC.read_text()

    header = extract_header(src_text)
    wrapper_header = strip_xif_ports(header).replace(
        "module x_heep_system", "module x_heep_system_synth_top", 1
    )

    xif_decls = "\n".join(f"  if_xif {sig}_i();" for sig, _modport in XIF_PORTS)
    xif_conns = ",\n".join(
        f"      .{sig}({sig}_i)" for sig, _modport in XIF_PORTS
    )

    wrapper = f"""\
// Auto-generated by scripts/synthesis/yosys/generate_xif_tieoff_wrapper.py
// from {SRC} - do not edit by hand, re-run the generator instead.
//
// Synthesis-only top: same parameter/port list as `x_heep_system` minus its
// 6 unconnected `if_xif` interface ports (tied off here to internal, unused
// interface instances, since no CPU extension is enabled in this flow).

{wrapper_header}

{xif_decls}

  x_heep_system x_heep_system_i (
      .*,
{xif_conns}
  );

endmodule
"""
    OUT.write_text(wrapper)
    print(f"[generate_xif_tieoff_wrapper] Wrote {OUT} (top: x_heep_system_synth_top)")


if __name__ == "__main__":
    main()
